apiVersion: v1
kind: Service
metadata:
  name: frontend-basic
spec:
  type: NodePort
  selector:
    app:  
  ports:
    - protocol: TCP
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.port }}
      nodePort: {{ .Values.service.nodePort }}

